manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-encoder
      url-base: https://github.com/tklzg
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk_encoder
      remote: zmk-encoder
      repo-path: zmk
      revision: encoder
      import: app/west.yml
  self:
    path: config
